server:
  port: 4004

  spring:
    cloud:
      gateway:
        routes:
          ## REST CLIENT ----> http://localhost:4004/api/patients
          ## (redirection) API GATEWAY ----> http://patient-service:4000/patients
          ## PATIENT SERVICE (Spring Boot app) ---> /patients ---> Patients Array

          - id: patient-service-route
            uri: http://patient-service:4000
            predicates:
              - path=/api/patients/**
            filters:
              - strip-prefix=1


          # Route for /api/docs/patients to patient-service /v3/api-docs
          - id: api-docs-patient-route
            uri: http://patient-service:4000
            predicates:
              - path=/api/patients
            filters:
              - rewrite-path=/api-docs/patients,/v3/api-docs
